Fix UB in `LinkedList::len`
conradludgate/linked_list_rs pull request #6
Opened 2022-06-11 21:30 UTC by Nilstrieb

According to the [Rust Reference](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html), dereferencing a null pointer is considered UB. When UB is encountered, anything is allowed to happen. Therefore, UB must be avoided.

This function is not unsafe, and must therefore never exhibit UB for any input provided to it.

This commit fixes the UB by always returning 0.

2022-06-11 21:31 UTC, conradludgate requested changes
Sorry I don't follow the rust spec. Vapourware. I follow my vibes

2022-06-11 21:33 UTC, Nilstrieb commented
What do your vibes say on this?

2022-06-11 21:34 UTC, Nilstrieb commented
Note that this is not the Rust spec (the Rust Programming Language has no specification), but the Rust Reference instead (`&Rust` for short).

2022-06-11 21:36 UTC, conradludgate commented
Is it a `&'static Rust` or a `for<'version> &'version Rust`

2022-06-11 21:38 UTC, Nilstrieb commented
It's a `&'static UnsafeCell<Rust>`, because multiple people work on it in parallel (like that one guy who wants to rewrite vec) and `Rust` is eternal.

2022-06-11 21:42 UTC, Nilstrieb commented
No answer for 3 minutes? Seems like this repo is unaintained. Someone get Rustsec on this.

2022-06-11 21:42 UTC, closed without merging

2022-06-11 21:42 UTC, conradludgate commented
Vibes were bad

2024-04-16 18:15 UTC, linkedlist771 commented
u guys made very funny conversation